

export default function Home() {
  return (
    <div>
      <h1 className="text-3xl font-bold">📚 Library Dashboard (SSG)</h1>
      <p>This page is statically generated by default.</p>
    </div>
  );
}
